### PR TITLE
remove Array spread operator and Array.find

### LINKED ISSUE #3: ES5 compatibility
### What problem does this feature solve?
When using this module, it requires some polyfills (like `Array.from` and `Array.find`) to work on old browsers like IE. As a low level module, I think it will be nice to provide compatibility to ES5 out of the box, so that the user doesn't need to worry about polyfills.

### PR DESCRIPTION
**Pull request by mjss**
Should fix #3 
ES6 spread operator is nice but Babel requires `Array.from` to transpile it (http://babeljs.io/docs/usage/caveats/#polyfills).
From our observation, the babel-transpiled code contains two ES6 methods: `Array.from` and `Array.find`. Refactoring the spread operator and `Array.find` can make this module support IE10+ without any polyfills.

### CODE REVIEW

**Comment by theKashey** [comment]
Oh, please excuse me, but I made all these changes in the morning, and just testing vue-lock before bulk release.

**Comment by theKashey** [comment]
I am not just very good in Vue, and having problems with a testing :)

**Comment by theKashey** [comment]
Could you double check that everything works as expected? And thank you. (and sorry for conflicts)

**Comment by mjss** [comment]
Great! I tested in our setup with IE10, v0.3.0 don't need the polyfills anymore :)

**Comment by mjss** [comment]
closing my PR

**Comment by theKashey** [comment]
Making things better is our duty.

**Pull request closed without merging**
